### ISSUE TITLE
why it doesnt have tf.contrib?

### ISSUE THREAD

**Issue by ibnux** [furas/tensorflow-no-avx#2]
`AttributeError: module 'tensorflow' has no attribute 'contrib'`

:(

**Comment by ibnux** [comment]
i use it for NudeNet

 [detector.py](https://github.com/notAI-tech/NudeNet/blob/8211bda0fe01c07a9d067252f42adcf27ca1b24d/nudenet/detector.py#L66)

**Comment by furas** [comment]
You have to import it 

```
import tensorflow.contrib
```

and later use `tensorflow.contrib` instead of `tf.contrib`
